source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'OriginateHTTP_Example', :exclusive => true do
  pod "OriginateHTTP", :path => "../"
end

target 'OriginateHTTP_Tests', :exclusive => true do
  pod "OriginateHTTP", :path => "../"

  
end
